---
title: "Miembros"
---

A continuación se presenta la lista de estudiantes que han participado de las actividades del Semillero, al dar clic sobre cada uno de los nombres usted podrá visitar la página web de cada uno de ellos.

## Semestre 2 de 2018

Aún no tenemos miembros para este semestre.

## Semestre 1 de 2018

- [Mateo Restrepo Higuita](https://marestrepohi.github.io)
- [Yuberth Anderson Saavedra Coneo](https://yuasaavedraco.github.io)
- [Angie Valeria López Echeverry](https://anvlopezec.github.io)
- [Dora Shirley Sánchez Sedano](https://dssanchezs.github.io)
- [Wendy Karen Rivera Tamayo](https://wkriverat.github.io)
- [Lina Maria Castillo Torres](https://lmcastillot.github.io)
- [Gustavo Adolfo González Hernández](https://gustavogonzalez1996.github.io/GustavoG)
- [Catalina Otálvaro Ramírez](https://caotalvarora.github.io)
- [Andrés Felipe Montoya Morales](https://toyaestadistico.github.io)
- [Brahian Cano Urrego](https://bencuben.github.io)
- [Julián Andres Mira Gomez](https://jamirag.github.io)
- [Santiago Toro Zuluaga](https://satorozu.github.io)
- [Julián Esteban Cadavid Cadavid](https://jcadavidc.github.io)
- [Luis Felipe Bedoya Martínez](https://felbed.github.io)
- [Andrés Felipe Cabrera Angulo](https://afcabreraa.github.io)
- [Yeison Yovany Ocampo Naranjo](https://yyocampon.github.io)
- [Yubar Daniel Marín Benjumea](https://ydmarinb.github.io)
- [Johan Felipe Mira Gil](https://jfmirag.github.io)
- [Paula Andrea Giraldo Pedroza](https://pagiraldop.github.io)
